# Generated by Django 4.2.8 on 2024-12-04 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunaapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='desription',
            new_name='description',
        ),
    ]
