# Generated by Django 4.2.8 on 2024-12-11 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tunaapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='songs',
            field=models.ManyToManyField(related_name='songs', through='tunaapi.SongGenre', to='tunaapi.song'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.TextField(max_length=45),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.TextField(max_length=80),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='tunaapi.artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='length',
            field=models.IntegerField(max_length=270),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.TextField(max_length=60),
        ),
        migrations.AlterField(
            model_name='songgenre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genresforsongs', to='tunaapi.genre'),
        ),
        migrations.AlterField(
            model_name='songgenre',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songgenre', to='tunaapi.song'),
        ),
    ]
